import { create } from 'zustand';
import { createConversationManagementActions } from './conversationStoreManagementActions';
import { createConversationMessageActions } from './conversationStoreMessageActions';
import type { ConversationState } from './conversationStoreSupport';

export {
  MAX_LOADED_MESSAGES,
  MESSAGE_PAGE_SIZE,
  clearLiveStreamContent,
  getLiveStreamContent,
  hasAuthoritativeMessageVersionSnapshot,
  invalidateConversationMessageCache,
  isObservedStreamingFor,
  selectUiMultiModelDoneMessageIds,
  selectUiMultiModelParentId,
  selectUiPendingCompanionModels,
  selectUiStreaming,
  selectUiStreamingConversationId,
  selectUiStreamingMessageId,
  setLiveStreamContent,
  snapshotStreamSyncState,
  subscribeLiveStreamContent,
} from './conversationStoreSupport';

export const useConversationStore = create<ConversationState>((set, get) => ({
  conversations: [],
  conversationsMeta: { status: 'idle', key: null, loadedAt: null, revision: 0 },
  messageVersionGroups: {},
  activeConversationId: null,
  messages: [],
  ragDisplayByMessageId: {},
  searchDisplayByMessageId: {},
  loading: false,
  loadingOlder: false,
  loadingNewer: false,
  hasOlderMessages: false,
  hasNewerMessages: false,
  totalActiveCount: 0,
  oldestLoadedMessageId: null,
  newestLoadedMessageId: null,
  streaming: false,
  observedStream: null,
  compressingConversationId: null,
  openCompressionSummaryToken: 0,
  streamingMessageId: null,
  streamingConversationId: null,
  activeStreamId: null,
  streamActivityByMessageId: {},
  thinkingActiveMessageIds: new Set<string>(),
  error: null,
  titleGeneratingConversationId: null,
  pendingCompanionModels: [],
  multiModelParentId: null,
  multiModelDoneMessageIds: [],
  pendingPromptText: null,
  setPendingPromptText: (text) => set({ pendingPromptText: text }),
  searchEnabled: false,
  searchProviderId: null,
  enabledMcpServerIds: [],
  thinkingBudget: null,
  thinkingLevel: null,
  enabledKnowledgeBaseIds: [],
  enabledMemoryNamespaceIds: [],
  multiModelTargets: [],
  multiModelContinuationMode: 'selected',
  archivedConversations: [],
  workspaceSnapshot: null,
  ...createConversationManagementActions(set, get),
  ...createConversationMessageActions(set, get),
}));
